"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
export function CustomerQuoteActions({ token, status }: { token: string; status: string }) {
  const [comment, setComment] = useState(""); const [message, setMessage] = useState<string>(); const [pending, setPending] = useState(false);
  async function send(action: "accepted" | "rejected" | "question") { setPending(true); setMessage(undefined); const response = await fetch(`/api/public/quotes/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, comment }) }); const payload = await response.json() as { error?: { message?: string } }; setPending(false); if (!response.ok) { setMessage(payload.error?.message ?? "Er ging iets mis. Probeer opnieuw."); return; } setMessage(action === "question" ? "Uw vraag is verstuurd. Het bedrijf neemt contact met u op." : action === "accepted" ? "Bedankt, de offerte is geaccepteerd." : "Uw reactie is doorgegeven."); }
  if (status !== "sent") return <p className="rounded-md bg-slate-100 p-4 text-sm">Deze offerte is al <strong>{status === "accepted" ? "geaccepteerd" : "afgewezen"}</strong>.</p>;
  return <section className="mt-8 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Uw beslissing</h2><p className="mt-1 text-sm text-slate-600">U kunt een opmerking of vraag achterlaten.</p><textarea className="mt-4 min-h-24 w-full rounded-md border border-slate-300 p-3 text-sm" value={comment} maxLength={2000} onChange={(event) => setComment(event.target.value)} placeholder="Uw opmerking of vraag (optioneel)" /><div className="mt-4 flex flex-wrap gap-3"><Button disabled={pending} onClick={() => send("accepted")}>Offerte accepteren</Button><Button disabled={pending} variant="outline" onClick={() => send("rejected")}>Afwijzen</Button><Button disabled={pending} variant="secondary" onClick={() => send("question")}>Stel een vraag</Button></div>{message && <p className="mt-4 text-sm text-slate-700">{message}</p>}</section>;
}
