"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { getTranslations } from "@/i18n/get-translations";
import type { SupportedLanguage } from "@/i18n/config";

export function CustomerQuoteActions({ token, status, language = "nl" }: { token: string; status: string; language?: SupportedLanguage }) {
  const { t } = getTranslations(language);
  const dutch = language === "nl";
  const [comment, setComment] = useState(""); const [message, setMessage] = useState<string>(); const [pending, setPending] = useState(false);
  async function send(action: "accepted" | "rejected" | "question") { setPending(true); setMessage(undefined); const response = await fetch(`/api/public/quotes/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, comment }) }); const payload = await response.json() as { error?: { message?: string } }; setPending(false); if (!response.ok) { setMessage(payload.error?.message ?? t("auth.registrationFailed")); return; } setMessage(dutch ? (action === "question" ? "Uw vraag is verstuurd. Het bedrijf neemt contact met u op." : action === "accepted" ? "Bedankt, de offerte is geaccepteerd." : "Uw reactie is doorgegeven.") : (action === "question" ? "Your question has been sent. The company will contact you." : action === "accepted" ? "Thank you, the quote has been accepted." : "Your response has been recorded.")); }
  if (status !== "sent") return <p className="rounded-md bg-slate-100 p-4 text-sm">{dutch ? "Deze offerte is al" : "This quote has already been"} <strong>{status === "accepted" ? (dutch ? "geaccepteerd" : "accepted") : (dutch ? "afgewezen" : "rejected")}</strong>.</p>;
  return <section className="mt-8 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">{dutch ? "Uw beslissing" : "Your decision"}</h2><p className="mt-1 text-sm text-slate-600">{dutch ? "U kunt een opmerking of vraag achterlaten." : "You can leave a comment or question."}</p><textarea className="mt-4 min-h-24 w-full rounded-md border border-slate-300 p-3 text-sm" value={comment} maxLength={2000} onChange={(event) => setComment(event.target.value)} placeholder={dutch ? "Uw opmerking of vraag (optioneel)" : "Your comment or question (optional)"} /><div className="mt-4 flex flex-wrap gap-3"><Button disabled={pending} onClick={() => send("accepted")}>{dutch ? "Offerte accepteren" : "Accept quote"}</Button><Button disabled={pending} variant="outline" onClick={() => send("rejected")}>{dutch ? "Afwijzen" : "Reject"}</Button><Button disabled={pending} variant="secondary" onClick={() => send("question")}>{dutch ? "Stel een vraag" : "Ask a question"}</Button></div>{message && <p className="mt-4 text-sm text-slate-700">{message}</p>}</section>;
}
