"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
type Task = { id: string; title: string; description: string | null; status: string; priority: string; due_at: string | null };
export function TaskManager({ companyId, tasks }: { companyId: string; tasks: Task[] }) {
  const router = useRouter(); const [title, setTitle] = useState(""); const [priority, setPriority] = useState("normal"); const [dueAt, setDueAt] = useState(""); const [openId, setOpenId] = useState<string>(); const [note, setNote] = useState(""); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function create(event: FormEvent) { event.preventDefault(); setPending(true); setError(undefined); const response = await fetch(`/api/v1/companies/${companyId}/tasks`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, priority, dueAt: dueAt || undefined }) }); setPending(false); if (!response.ok) { const data = await response.json() as { error?: { message?: string } }; setError(data.error?.message ?? "Taak maken mislukt."); return; } setTitle(""); setDueAt(""); router.refresh(); }
  async function update(taskId: string, changes: Record<string, unknown>) { const response = await fetch(`/api/v1/companies/${companyId}/tasks`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ taskId, ...changes }) }); if (!response.ok) { setError("Taak kon niet worden bijgewerkt."); return false; } router.refresh(); return true; }
  async function finish(taskId: string, done: boolean) { await update(taskId, { status: done ? "todo" : "done" }); }
  function open(task: Task) { setOpenId(task.id); setNote(task.description ?? ""); }
  async function saveNote(taskId: string) { if (await update(taskId, { description: note })) setOpenId(undefined); }
  async function remove(taskId: string) { if (!window.confirm("Weet je zeker dat je deze taak wilt verwijderen?")) return; const response = await fetch(`/api/v1/companies/${companyId}/tasks?taskId=${taskId}`, { method: "DELETE" }); if (!response.ok) { setError("Taak verwijderen mislukt."); return; } if (openId === taskId) setOpenId(undefined); router.refresh(); }
  return <div className="space-y-6"><form onSubmit={create} className="grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 md:grid-cols-[1fr_150px_150px_auto]"><input className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Nieuwe taak, bijvoorbeeld: klant terugbellen" required minLength={2} /><select className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm" value={priority} onChange={(event) => setPriority(event.target.value)}><option value="low">Laag</option><option value="normal">Normaal</option><option value="high">Hoog</option><option value="urgent">Urgent</option></select><input className="rounded-md border border-slate-300 bg-white px-3 py-2 text-sm" type="date" value={dueAt} onChange={(event) => setDueAt(event.target.value)} /><Button disabled={pending}>{pending ? "Opslaan…" : "Taak toevoegen"}</Button></form>{error && <p className="text-sm text-red-600">{error}</p>}<div className="divide-y">{tasks.map((task) => <div key={task.id} className="py-3"><div className="flex items-center justify-between gap-4"><label className="flex min-w-0 items-center gap-3"><input aria-label={`Taak ${task.title} afronden`} checked={task.status === "done"} type="checkbox" onChange={() => finish(task.id, task.status === "done")} /><button className={task.status === "done" ? "text-left text-slate-400 line-through" : "text-left font-medium hover:text-blue-700"} type="button" onClick={() => open(task)}>{task.title}</button></label><div className="flex shrink-0 items-center gap-3"><p className="text-sm text-slate-600">{task.due_at ? new Date(task.due_at).toLocaleDateString("nl-NL") : "Geen deadline"}</p><button type="button" className="text-sm text-red-600 hover:underline" onClick={() => remove(task.id)}>Verwijder</button></div></div><p className="ml-7 mt-1 text-sm text-slate-600">{task.priority} · {task.status}{task.description ? " · notitie aanwezig" : ""}</p>{openId === task.id && <div className="ml-7 mt-3 rounded-md bg-slate-50 p-3"><label className="block text-sm font-medium">Notitie</label><textarea className="mt-2 min-h-24 w-full rounded-md border border-slate-300 bg-white p-2 text-sm" value={note} maxLength={2000} onChange={(event) => setNote(event.target.value)} placeholder="Extra informatie, afspraaknotities of aandachtspunten" /><div className="mt-2 flex gap-2"><Button type="button" onClick={() => saveNote(task.id)}>Notitie opslaan</Button><Button type="button" variant="outline" onClick={() => setOpenId(undefined)}>Sluiten</Button></div></div>}</div>)}{tasks.length === 0 && <p className="py-8 text-sm text-slate-600">Nog geen taken. Voeg hierboven de eerste taak toe.</p>}</div></div>;
}
