"use client";

import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { getTranslations } from "@/i18n/get-translations";

export type CompanyProfile = { name: string; kvkNumber: string; vatNumber: string; iban: string; street: string; postalCode: string; city: string; country: string; phone: string; email: string; website: string; logoUrl: string };

export function CompanyProfileForm({ companyId, profile }: { companyId: string; profile: CompanyProfile }) {
  const { t } = getTranslations(); const [state, setState] = useState(profile); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string>();
  const set = (key: keyof CompanyProfile, value: string) => setState((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); setPending(true); setMessage(undefined); try { const response = await fetch(`/api/v1/companies/${companyId}/profile`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(state) }); if (!response.ok) throw new Error(); setMessage(t("companyProfile.saved")); } catch { setMessage(t("companyProfile.saveFailed")); } finally { setPending(false); } }
  return <form onSubmit={save} className="mt-6 space-y-6"><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="text-sm font-medium">{t("companyProfile.identity")}</legend><Field label={t("companyProfile.name")} value={state.name} required onChange={(value) => set("name", value)} /><Field label={t("companyProfile.kvk")} value={state.kvkNumber} onChange={(value) => set("kvkNumber", value)} /><Field label={t("companyProfile.vat")} value={state.vatNumber} onChange={(value) => set("vatNumber", value)} /><Field label={t("companyProfile.iban")} value={state.iban} onChange={(value) => set("iban", value)} /><Field label={t("companyProfile.logo")} value={state.logoUrl} type="url" onChange={(value) => set("logoUrl", value)} /></fieldset><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="text-sm font-medium">{t("companyProfile.address")}</legend><Field label={t("companyProfile.street")} value={state.street} onChange={(value) => set("street", value)} /><Field label={t("companyProfile.postalCode")} value={state.postalCode} onChange={(value) => set("postalCode", value)} /><Field label={t("companyProfile.city")} value={state.city} onChange={(value) => set("city", value)} /><Field label={t("companyProfile.country")} value={state.country} onChange={(value) => set("country", value)} /></fieldset><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="text-sm font-medium">{t("companyProfile.contact")}</legend><Field label={t("companyProfile.phone")} value={state.phone} type="tel" onChange={(value) => set("phone", value)} /><Field label={t("companyProfile.email")} value={state.email} type="email" onChange={(value) => set("email", value)} /><Field label={t("companyProfile.website")} value={state.website} type="url" onChange={(value) => set("website", value)} /></fieldset><div className="flex items-center gap-3"><Button disabled={pending}>{pending ? t("companyProfile.saving") : t("companyProfile.save")}</Button>{message && <p role="status" className="text-sm text-slate-700">{message}</p>}</div></form>;
}

function Field({ label, value, onChange, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string }) { return <label className="text-sm">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded border bg-white px-3 py-2" /></label>; }
