import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
const addSchema = z.object({ email: z.string().trim().email().max(254), role: z.enum(["employee", "technician"]) });
const updateSchema = z.object({ userId: z.string().uuid(), role: z.enum(["employee", "technician"]) });
async function owner(companyId: string) { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return { supabase, error: NextResponse.json({ error: { message: "Log opnieuw in." } }, { status: 401 }) }; const { data } = await supabase.from("company_memberships").select("role").eq("company_id", companyId).eq("user_id", user.id).maybeSingle(); if (data?.role !== "owner") return { supabase, error: NextResponse.json({ error: { message: "Alleen een eigenaar mag teamleden beheren." } }, { status: 403 }) }; return { supabase, error: null }; }
export async function POST(request: Request, { params }: { params: Promise<{ companyId: string }> }) { const input = addSchema.safeParse(await request.json()); if (!input.success) return NextResponse.json({ error: { message: "Controleer e-mail en rol." } }, { status: 400 }); const { companyId } = await params; const access = await owner(companyId); if (access.error) return access.error; const { error } = await access.supabase.rpc("add_company_member_by_email", { target_company_id: companyId, target_email: input.data.email, target_role: input.data.role }); if (error) return NextResponse.json({ error: { message: error.message } }, { status: 409 }); return NextResponse.json({ ok: true }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ companyId: string }> }) { const input = updateSchema.safeParse(await request.json()); if (!input.success) return NextResponse.json({ error: { message: "Ongeldige rol." } }, { status: 400 }); const { companyId } = await params; const access = await owner(companyId); if (access.error) return access.error; const { error } = await access.supabase.from("company_memberships").update({ role: input.data.role }).eq("company_id", companyId).eq("user_id", input.data.userId); if (error) return NextResponse.json({ error: { message: "Rol kon niet worden bijgewerkt." } }, { status: 500 }); return NextResponse.json({ ok: true }); }
export async function DELETE(request: Request, { params }: { params: Promise<{ companyId: string }> }) { const userId = new URL(request.url).searchParams.get("userId"); if (!userId || !z.string().uuid().safeParse(userId).success) return NextResponse.json({ error: { message: "Ongeldige gebruiker." } }, { status: 400 }); const { companyId } = await params; const access = await owner(companyId); if (access.error) return access.error; const { error } = await access.supabase.from("company_memberships").delete().eq("company_id", companyId).eq("user_id", userId).neq("role", "owner"); if (error) return NextResponse.json({ error: { message: "Teamlid kon niet worden verwijderd." } }, { status: 500 }); return NextResponse.json({ ok: true }); }
