"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
type Member = { user_id: string; role: string; users: { email: string; full_name: string | null } | null };
type Invitation = { id: string; email: string; role: string; status: string; expires_at: string };
export function TeamManager({ companyId, members, invitations }: { companyId: string; members: Member[]; invitations: Invitation[] }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [role, setRole] = useState("employee"); const [message, setMessage] = useState<string>(); const [token, setToken] = useState<string>();
  async function request(url: string, method: string, body?: unknown) { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json() as { error?: { message?: string }; invitation?: { token?: string } }; if (!response.ok) { setMessage(data.error?.message ?? "Wijziging mislukt."); return false; } if (data.invitation?.token) setToken(data.invitation.token); router.refresh(); return true; }
  async function add(event: FormEvent) { event.preventDefault(); if (await request(`/api/v1/companies/${companyId}/invitations`, "POST", { email, role })) { setEmail(""); setMessage("Uitnodiging aangemaakt. E-mailverzending is niet actief."); } }
  return <div className="space-y-5"><form onSubmit={add} className="grid gap-3 rounded-lg border bg-slate-50 p-4 md:grid-cols-[1fr_150px_auto]"><input className="rounded-md border border-slate-300 p-2 text-sm" type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="E-mailadres van bestaand account" required /><select className="rounded-md border border-slate-300 p-2 text-sm" value={role} onChange={(e) => setRole(e.target.value)}><option value="employee">Medewerker</option><option value="technician">Monteur</option></select><Button>Uitnodiging aanmaken</Button></form><p className="text-sm text-slate-600">E-mailverzending is uitgeschakeld. Toon de eenmalige link alleen aan de bedoelde persoon.</p>{token && <p className="rounded-md bg-amber-50 p-3 text-sm">Eenmalige testtoken (bewaar hem veilig): <code className="break-all">{token}</code></p>}{message && <p className="text-sm text-slate-700">{message}</p>}<h2 className="font-semibold">Actieve teamleden</h2><div className="divide-y">{members.map((member) => <div className="flex flex-wrap items-center justify-between gap-3 py-4" key={member.user_id}><div><p className="font-medium">{member.users?.full_name ?? member.users?.email ?? "Gebruiker"}</p><p className="text-sm text-slate-600">{member.users?.email}</p></div>{member.role === "owner" ? <p className="text-sm">Eigenaar</p> : <div className="flex items-center gap-2"><select className="rounded-md border border-slate-300 p-2 text-sm" value={member.role} onChange={(e) => request(`/api/v1/companies/${companyId}/members`, "PATCH", { userId: member.user_id, role: e.target.value })}><option value="employee">Medewerker</option><option value="technician">Monteur</option></select><button className="text-sm text-red-600 hover:underline" onClick={() => { if (window.confirm("Teamlid verwijderen?")) request(`/api/v1/companies/${companyId}/members?userId=${member.user_id}`, "DELETE"); }}>Verwijder</button></div>}</div>)}</div><h2 className="font-semibold">Openstaande uitnodigingen</h2><div className="divide-y">{invitations.filter((invitation) => invitation.status === "pending").map((invitation) => <div className="flex items-center justify-between gap-3 py-3" key={invitation.id}><div><p>{invitation.email}</p><p className="text-sm text-slate-600">{invitation.role === "technician" ? "Monteur" : "Medewerker"} · verloopt {new Date(invitation.expires_at).toLocaleDateString("nl-NL")}</p></div><button className="text-sm text-red-600 hover:underline" onClick={() => request(`/api/v1/companies/${companyId}/invitations/${invitation.id}`, "DELETE")}>Intrekken</button></div>)}</div></div>;
}
